---
- name: Install java and net-tools
  hosts: ec2
  become: yes
  tasks:
  - name: Update package manager
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install Java 8
    apt: name=openjdk-8-jre-headless
  - name: Install net-tools
    apt: name=net-tools
  - name: Install ACL
    apt: name=acl

- name: Download and unpack Nexus installer
  hosts: ec2
  become: yes
  gather_facts: false
  tasks:
  - name: Check if Nexus folder already exists
    stat: 
      path: /opt/nexus
    register: stat_result
  - name: Download Nexus
    get_url: 
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /opt/
    register: download_result
  - name: Unpack Nexus installer
    unarchive: 
      src: "{{ download_result.dest }}"
      dest: /opt/
      remote_src: yes
    when: not stat_result.stat.exists
  - name: Find Nexus folder path
    find: 
      paths: /opt/
      pattern: "nexus-*"
      file_type: directory
    register: find_result
  - name: Rename Nexus folder (skip if folder already exists)
    shell: mv {{find_result.files[0].path}} /opt/nexus/
    when: not stat_result.stat.exists

- name: Create nexus user to own nexus folder
  hosts: ec2
  become: yes
  gather_facts: false
  tasks:
  - name: Create Nexus group
    group:
      name: nexus
      state: present
  - name: Create Nexus user
    user:
      name: nexus
      group: nexus
      state: present
  - name: Make new user owner of nexus folder
    file: 
      path: /opt/nexus
      state: directory
      owner: nexus
      group: nexus
      recurse: yes
  - name: Make new user owner of sonatype-work folder
    file: 
      path: /opt/sonatype-work
      state: directory
      owner: nexus
      group: nexus
      recurse: yes


- name: Start Nexus with nexus user
  hosts: ec2
  become: yes
  gather_facts: false
  tasks:
  - name: Set run as user_nexus
    lineinfile:
      path: /opt/nexus/bin/nexus.rc
      regexp: '^#run_as_user=""'
      line: run_as_user="nexus"
  - name: Run Nexus
    command: /opt/nexus/bin/nexus start
    become_user: nexus

- name: Verify Nexus is running
  hosts: ec2
  gather_facts: false
  tasks:
  - name: Wait 1 minute
    pause: 
      minutes: 1
  - name: Check with "ps aux"  
    shell: ps aux | grep nexus   
    register: app_status
  - debug: msg={{app_status.stdout_lines}}
  - name: Check with "netstat"  
    shell: netstat -tlpn  
    register: app_status
  - debug: msg={{app_status.stdout_lines}}